services:
    app:
        build:
            context: .
            target: development
            args:
                # UID and GID must be set as environment variables on the host machine
                USER_ID: 1001
                GROUP_ID: 1001
        container_name: app-kost
        restart: unless-stopped
        environment:
            - COMPOSER_HOME=~/.composer
        ports:
            - 8003:8080
        volumes:
            - .:/var/www/html

    queue:
        build:
            context: .
            target: development
            args:
                # UID and GID must be set as environment variables on the host machine
                USER_ID: 1001
                GROUP_ID: 1001
        volumes:
            - .:/var/www/html
        command: ["php", "/var/www/html/artisan", "queue:work"]
        environment:
            - PHP_FPM_POOL_NAME="my-app_queue"
        healthcheck:
            # This is our native healthcheck script for the queue
            test: ["CMD", "healthcheck-queue"]
            start_period: 10s
        restart: on-failure

    schedule:
        build:
            context: .
            target: development
            args:
                # UID and GID must be set as environment variables on the host machine
                USER_ID: 1001
                GROUP_ID: 1001
        volumes:
            - .:/var/www/html
        command: ["php", "/var/www/html/artisan", "schedule:work"]
        environment:
            - PHP_FPM_POOL_NAME="my-app_schedule"
        healthcheck:
            # This is our native healthcheck script for the queue
            test: ["CMD", "healthcheck-schedule"]
            start_period: 10s
        restart: on-failure

networks:
    default:
        external: true
        name: laravel
